### ISSUE TITLE
SETBIT operation should not have bitwise negation on value

### ISSUE THREAD

**Issue by lhoyosm** [rumpeltux/stm8s-sdcc-examples#1]
SETBIT operation should not have bitwise negation on value
https://github.com/rumpeltux/stm8s-sdcc-examples/blob/e54983d4f5f29466e8913cce7115569e9544a10b/serial_interrupt.c#L13

**Comment by rumpeltux** [comment]
Ouch. Thanks for letting me know!
Does the example still work with the definition fixed?

**Comment by lhoyosm** [comment]
unfortunately I don't have the hardware to test it yet, next week or so I can report...

**Comment by lhoyosm** [comment]
Tested and working! #2

**Comment by rumpeltux** [comment]
Thanks for noticing and fixing!

**Comment by rumpeltux** [comment]
This was fixed in 450196c7
